### ISSUE TITLE
Minor issues with Instructions field type

### ISSUE THREAD

**Issue by liamjones** [webhook/webhook-cms#193]
1. Instructions visually change width when selected for editing (http://cl.ly/Z0g2)
2. Error styling is incorrect (http://cl.ly/Z12B)
3. Related to point 2 - _should_ Webhook refuse to allow instruction fields which have the same label?
4. Are instructions meant to be available to the front end? They aren't listed in the docs (http://www.webhook.com/docs/widget-template-reference/) but the scaffold will generate output for them (only a label, no value obviously)

**Comment by gpbmike** [comment]
Sorry for the slow response.

1. This is as intended.
1. The error styling on the fields with errors is correct. Did the instruction text change to be the error? I was not able to reproduce that when I tried.
1. This has been fixed.
1. It doesn't hurt to have instructions available in the templates. 

Let me know if you have any follow-up questions.
