### ISSUE TITLE
WYSIWYG improvements

### ISSUE THREAD

**Issue by snide** [webhook/webhook-cms#204]
The following problems with the WYSIWYG make it hard to use currently.

1. You can't paste embeds into the code view. If there is a script tag or something in them (ex: twitter) it gets removed. We shouldn't worry too much about script tags since this is all behind a wall.
2. Trying to document code in the wysiwyg is very hard. It autoescapes everything so you can't edit it after the fact. It would be nice if it syntax highlighting and some form of tabbing could be used in these. Right now code highlighting needs to be done through JS on the frontend side. Would be amazing if the content somehow came over rendered so all we'd need is a css file.
3. There are some alignment issues. Often when moving content from the left/right/center/up/down, the editor cursor will jump to the top of the document.

**Comment by gpbmike** [comment]
Moved to webhook-redactor repo.
