### ISSUE TITLE
Rating Widget don't work on Firefox

### ISSUE THREAD

**Issue by geekpobre** [webhook/webhook-cms#209]
Hello,
I'm trying to use the rating widget on Firefox (33 and 34) on Windows and OSX and it doesn't work on any combination of OS and Browser. The hover effect don't happen and if i click on a star it does not fill them correctly, instead the browser just select the stars.
Here is a quick gif showing what happens when i move the mouse and click on the stars.
![rating](https://cloud.githubusercontent.com/assets/265922/5680774/ea0e6080-97f8-11e4-8b0a-02459386c266.gif)

**Comment by gpbmike** [comment]
Thanks for pointing that out and illustrating with a gif. This is fixed and live now.
